Repository pexip/shared-github-actions, pull requests merged in 2023-11, with the labels that each got.

#16 Add support for specifying repository
  .github/actions/docker-build-gcp/action.yml
  .github/actions/release/action.yml
  .github/actions/terraform-deploy-gcp/action.yml
  examples/development.yml
  examples/production.yml
Labels: change, maintenance

#17 Added pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/actions/docker-build-gcp/action.yml
Labels: change

#18 Added missing tag input variable
  .github/actions/docker-build-gcp/action.yml
Labels: bug

#19 Moved pull request template
  .github/pull_request_template.md
Labels: bug

#20 changed input.TAG -> inputs.tag
  .github/actions/docker-build-gcp/action.yml
Labels: bug
